-- Catálogo de parámetros — descripciones, tipo de campo, valores predeterminados y referencia.
-- Fuente: tabla Parámetros del sistema Access (PDF relevado julio 2026, completo).
-- Parámetros SIN prefijo (-) son los comprendidos en el alcance de la acreditación O.U.A. LE 006.
-- Parámetros CON prefijo (-) NO están acreditados.
-- Se puede correr varias veces: ON CONFLICT actualiza todos los campos.

INSERT INTO parametros (codigo, descripcion, tipo_campo, valor_predeterminado, valor_referencia)
VALUES
-- ── ACREDITADOS (sin prefijo "(-)")  ────────────────────────────────────────
('0003', '(1) Coliformes Totales ufc / 100 ml',                          'texto',   '<1',              '< 1 ufc/100 ml'),
('0004', '(2) Coliformes Termotolerantes (Fecales) ufc / 100 ml',        'texto',   '<1',              '< 1 ufc/100 ml'),
('0013', 'Aerobios Totales (ufc/g)',                                      'texto',   '<1.0*10(1)',      NULL),
('0014', 'Salmonella spp (en 25 g)',                                      'ausencia','Ausencia',        NULL),
('0026', 'Recuentos Totales (ufc/ml)',                                    'texto',   '<1',              NULL),
('0052', 'Enterobacterias (ufc/g)',                                       'texto',   '<1.0*10(1)',      NULL),
('0055', 'E.coli O157:H7 (en 325 g)',                                    'negativo','Negativo',        NULL),
('0056', 'Enterobacterias (ufc/ml)',                                      'texto',   '<1',              NULL),
('0064', 'Salmonella spp (en 125 g)',                                     'ausencia','Ausencia',        NULL),
('0070', 'Enterobacterias (ufc/cm2)',                                     'texto',   NULL,              NULL),
('0071', 'Salmonella spp (en 25 ml)',                                     'negativo','Negativo',        NULL),
('0077', '(3) E coli (ufc/100mL)',                                        'texto',   '<1',              '< 1 ufc/100 mL'),
('0083', 'Listeria monocytogenes (en 25 g)',                              'ausencia','Ausencia',        NULL),
('0085', 'E coli STEC screening (en 325 g)',                              'negativo','Negativo',        NULL),
('0086', 'E coli O26 (en 325 g)',                                         'negativo','Negativo',        NULL),
('0087', 'E coli O45 (en 325 g)',                                         'negativo','Negativo',        NULL),
('0088', 'E coli O103 (en 325 g)',                                        'negativo','Negativo',        NULL),
('0089', 'E coli O111 (en 325 g)',                                        'negativo','Negativo',        NULL),
('0090', 'E coli O121 (en 325g)',                                         'negativo','Negativo',        NULL),
('0091', 'E coli O145 (en 325g)',                                         'negativo','Negativo',        NULL),
('0123', 'E coli O157:NM (en 325g)',                                      'negativo','Negativo',        NULL),
('0127', 'Salmonella (en 125 g)',                                         'negativo','Negativo',        NULL),
('0129', 'E coli STEC serotipo O (en 325 g)',                             'negativo','Negativo',        NULL),
('0138', 'Recuentos Totales (ufc/cm2)',                                   'texto',   NULL,              NULL),
('0144', 'Salmonella spp (en 125 g)',                                     'negativo','Negativo',        NULL),
('0145', 'Salmonella spp (en 25 g)',                                      'negativo','Negativo',        NULL),
('50',   'Salmonella spp (en 25 ml)',                                     'ausencia','Ausencia',        NULL),

-- ── NO ACREDITADOS (prefijo "(-)")  ─────────────────────────────────────────
('0001', '(-) ufc/ ml a 37° C / 44 h',                                   'texto',   '<1',              '<= 10 ufc/mL'),
('0002', '(-) ufc/ ml a 22° C / 68 h',                                   'texto',   '<1',              '<= 100 ufc/mL'),
('0005', '(-) Cloro Residual (ppm)',                                      'texto',   '<0.1',            NULL),
('0006', '(-) Clasificación',                                             'texto',   NULL,              NULL),
('0007', '(-) Estreptococos Fecales ufc/ 100 ml',                        'texto',   '<1',              NULL),
('0008', '(-) Clostridios Sulfito Reductores ufc/ 100 ml',               'texto',   '<1',              '< 1 ufc/100 mL'),
('0010', '(-) E.coli (ufc/g)',                                            'texto',   '<1.0*10(1)',      NULL),
('0011', '(-) Coliformes Totales (ufc/g)',                                'texto',   '<1.0*10(1)',      NULL),
('0012', '(-) Coliformes Fecales (NMP/g)',                                'texto',   '<3.0',            NULL),
('0015', '(-) Staphylococcus aureus (ufc/cm2)',                           'texto',   '<1.0*10(1)',      NULL),
('0016', '(-) E.coli (ufc/cm2)',                                          'texto',   '<0.083',          NULL),
('0017', '(-) E.coli (ufc/ml)',                                           'texto',   '<1',              NULL),
('0018', '(-) Coliformes Totales (ufc/ml)',                               'texto',   '<1',              NULL),
('0019', '(-) Recuentos Totales (ufc/ml)',                                'texto',   '<1',              NULL),
('0020', '(-) Listeria monocytogenes (en 25 g)',                          'ausencia','Ausencia',        NULL),
('0021', '(-) Nitritos ppm (mg NaNO2 /Kg de muestra)',                   'texto',   '<10',             NULL),
('0023', '(-) Pseudomonas aeruginosa (ufc/ 100 ml)',                     'texto',   '<1',              '<1 ufc/100mL'),
('0024', '(-) Staphylococcus aureus (ufc/g)',                             'texto',   '<1.0*10(1)',      NULL),
('0025', '(-) Bacillus cereus',                                           'texto',   NULL,              NULL),
('0027', '(-) Coliformes Fecales (ufc/ml)',                               'texto',   '<1',              NULL),
('0028', '(-) Coliformes Totales (NMP/g)',                                'texto',   '<3.0',            NULL),
('0029', '(-) Coliformes Totales (ufc/cm2)',                              'texto',   '<1',              NULL),
('0030', '(-) Aerobios mesófilos (ufc/g)',                                'texto',   '<1.0*10(1)',      NULL),
('0032', '(-) Salmonella spp (en 25 g)',                                  'negativo','Negativo',        NULL),
('0033', '(-) Listeria spp (en 3 ml)',                                    'ausencia','Ausencia',        NULL),
('0034', '(-) Nitratos ppm (mg NaNO3 /Kg de muestra)',                   'texto',   '<10',             NULL),
('0035', '(-) E. coli O157:H7 (en 25 g)',                                'negativo','Negativo',        NULL),
('0036', '(-) Hongos y levaduras (ufc / g)',                              'texto',   '<1.0*10(1)',      NULL),
('0037', '(-) % Grasa',                                                   'texto',   NULL,              NULL),
('0038', '(-) % Humedad',                                                 'texto',   NULL,              NULL),
('0039', '(-) % Proteina',                                                'texto',   NULL,              NULL),
('0040', '(-) pH',                                                        'texto',   NULL,              NULL),
('0041', '(-) Salmonella spp',                                            'texto',   NULL,              NULL),
('0042', '(-) Coliformes Fecales (ufc/g)',                                'texto',   '<1.0*10(1)',      NULL),
('0043', '(-) % Cenizas',                                                 'texto',   NULL,              NULL),
('0044', '(-) Plomo ppm (mg Pb/Kg)',                                      'texto',   '<0.05',           NULL),
('0045', '(-) % NaCl',                                                    'texto',   NULL,              NULL),
('0046', '(-) Pseudomonas spp (ufc/ 100ml)',                              'texto',   '<1',              '<1 ufc/100mL'),
('0047', '(-) Recuentos Totales (ufc/cm2)',                               'texto',   '<1',              NULL),
('0048', '(-) E coli O145 (en 325g)',                                     'negativo','Negativo',        NULL),
('0049', '(-) Clostridios Sulfito Reductores (en 25 g)',                  'ausencia','Ausencia',        NULL),
('0050', '(-) Salmonella spp (cm2)',                                      'negativo','Negativo',        NULL),
('0051', '(-) E. coli O157:H7',                                           'negativo','Negativo',        NULL),
('0053', '(-) Salmonella spp (en 250 g)',                                 'texto',   NULL,              NULL),
('0054', '(-) E. coli O157:H7 (en 25 g)',                                'negativo','Negativo',        NULL),
('0057', '(-) E.coli (ufc/ 100ml)',                                       'texto',   NULL,              NULL),
('0058', '(-) E coli STEC screening (en 325 g)',                          'negativo','Negativo',        NULL),
('0059', '(-) Salmonella spp (en 100 cm2)',                               'ausencia','Ausencia',        NULL),
('0060', '(-) Salmonella spp (en 100 cm2)',                               'ausencia','Ausencia',        NULL),
('0061', '(-) Shigella (en 25 g)',                                        'ausencia','Ausencia',        NULL),
('0062', '(-) Salmonella spp (en 125 g)',                                 'negativo','Negativo',        NULL),
('0063', '(-) Salmonella (en 325 g)',                                     'ausencia','Ausencia',        NULL),
('0065', '(-) Enterobacterias (ufc/g)',                                   'texto',   '<1.0*10(1)',      NULL),
('0066', '(-) E coli O157:H7 (en 65g)',                                   'negativo','Negativo',        NULL),
('0067', '(-) Heterótrofos (ufc/g)',                                      'texto',   '<1.0*10(1)',      NULL),
('0068', '(-) Listeria spp (en 25g)',                                     'ausencia','Ausencia',        NULL),
('0069', '(-) Recuentos Totales (ufc/g)',                                 'texto',   '<1.0*10(1)',      NULL),
('0072', '(-) Salmonella spp (250 ml)',                                   'texto',   NULL,              NULL),
('0073', '(-) Recuentos totales (ufc/ml)',                                'texto',   '<1',              NULL),
('0074', '(-) Listeria monocytógenes (en 25g)',                           'ausencia','Ausencia',        NULL),
('0075', '(-) Salmonella spp (en 50g)',                                   'texto',   NULL,              NULL),
('0076', '(-) Enterococos (ufc/100mL)',                                   'texto',   '<1',              '< 1 ufc/100 mL'),
('0078', '(-) Salmonella spp (en 400 cm2)',                               'texto',   NULL,              NULL),
('0079', '(-) Listeria monocytogenes (en 3ml)',                           'ausencia','Ausencia',        NULL),
('0080', '(-) Clostridium Perfringens (ufc/100ml)',                       'texto',   '<1',              NULL),
('0081', '(-) Clasificación',                                             'texto',   NULL,              NULL),
('0082', '(-) Listeria monocytogenes (en 25 g)',                          'ausencia','Ausencia',        NULL),
('0084', '(-) Coliformes Termotolerantes (ufc/g)',                        'texto',   '<1.0*10(1)',      NULL),
('0092', '(-) Listeria monocytogenes (en 25 mL)',                         'ausencia','Ausencia',        NULL),
('0093', '(-) Clostridium perfringes (ufc/g)',                            'texto',   '<1.0*10(1)',      NULL),
('0094', '(-) Levaduras (ufc/g)',                                         'texto',   '<1.0*10(1)',      NULL),
('0095', '(-) Clostridium sulfito reductores (ufc/g)',                    'texto',   '<1.0*10(1)',      NULL),
('0096', '(-) E coli STEC (stx) (en 325 g)',                             'negativo','Negativo',        NULL),
('0097', '(-) E coli STEC (en 325 g)',                                    'negativo','Negativo',        NULL),
('0098', '(-) E coli STEC (stx) (en 325 g)',                             'negativo','Negativo',        NULL),
('0099', '(-) E coli STEC (eae) (en 325 g)',                             'negativo','Negativo',        NULL),
('0100', '(-) M1 stx (65 g)',                                             'negativo','Negativo',        NULL),
('0101', '(-) M1 eae (65 g)',                                             'negativo','Negativo',        NULL),
('0102', '(-) M2 stx (65 g)',                                             'negativo','Negativo',        NULL),
('0103', '(-) M2 eae (65 g)',                                             'negativo','Negativo',        NULL),
('0104', '(-) M3 stx (65 g)',                                             'negativo','Negativo',        NULL),
('0105', '(-) M3 eae (65 g)',                                             'negativo','Negativo',        NULL),
('0106', '(-) M4 stx (65 g)',                                             'negativo','Negativo',        NULL),
('0107', '(-) M4 eae (65 g)',                                             'negativo','Negativo',        NULL),
('0108', '(-) M5 stx (65 g)',                                             'negativo','Negativo',        NULL),
('0109', '(-) M5 eae (65 g)',                                             'negativo','Negativo',        NULL),
('0110', '(-) E coli O26 (en 65g)',                                       'negativo','Negativo',        NULL),
('0111', '(-) E coli O45 (en 65g)',                                       'negativo','Negativo',        NULL),
('0112', '(-) E coli O103 (en 65g)',                                      'negativo','Negativo',        NULL),
('0113', '(-) E coli O111 (en 65g)',                                      'negativo','Negativo',        NULL),
('0114', '(-) E coli O121 (en 65g)',                                      'negativo','Negativo',        NULL),
('0115', '(-) E coli O145 (en 65g)',                                      'negativo','Negativo',        NULL),
('0116', '(-) actividad bactericida',                                     'texto',   NULL,              NULL),
('0117', '(-) Enterococos (ufc/g)',                                       'texto',   NULL,              NULL),
('0118', '(-) Mesófilos anaerobios facultativos (ufc/g)',                 'texto',   '<1.0*10(1)',      NULL),
('0119', '(-) Bacterias Mesófilas Acido Lácticas (ufc/g)',               'texto',   '<1.0*10(1)',      NULL),
('0120', '(-) Relación Bacterias Mesófilas Acido Lácticas/ Aerobios Mesófilos', 'texto', '<1',         NULL),
('0121', '(-) Listeria monocytogenes (en 25 mL)',                         'ausencia','Ausencia',        NULL),
('0122', '(-) E coli O157:H7 (en 325g)',                                  'negativo','Negativo',        NULL),
('0124', '(-) Listeria spp (en 25mL)',                                    'ausencia','Ausencia',        NULL),
('0125', '(-) Calcio (mg/Kg)',                                            'texto',   NULL,              NULL),
('0126', '(-) Coliformes Termotolerantes (ufc/100mL)',                    'texto',   '<1',              NULL),
('0128', '(-) Recuentos Totales (ufc/mL)',                                'texto',   '<1',              NULL),
('0130', '(-) Heterótrofos ufc/mL a 37° C',                              'texto',   NULL,              '<= 500 ufc/mL'),
('0131', '(-) Pseudomona ufc/100mL',                                      'ausencia','Ausencia',        'Ausencia'),
('0132', '(-) Listeria monocytogenes (en 25 mL)',                         'negativo','Negativo',        NULL),
('0133', '(-) Bacterias ácido lácticas (ufc/g)',                          'texto',   '<1.0*10(1)',      NULL),
('0134', '(-) Pseudomona spp (en 25 g)',                                  'ausencia','Ausencia',        NULL),
('0135', '(-)(2) Coliformes Termotolerantes (Fecales) ufc / 100 ml',     'texto',   '<1',              '<1 UFC/100ML'),
('0136', '(-)(3) E coli (ufc/100mL)',                                     'texto',   '<1',              '<1 UFC/100ML'),
('0137', '(-) Listeria monocytógenes (en 125g)',                          'ausencia','Ausencia',        NULL),
('0139', '(-) E coli STEC (stx,eae) (en 325g)',                          'negativo','Negativo',        NULL),
('0146', '(-) Salmonella spp (en 25 ml)',                                 'negativo','Negativo',        NULL),
('0150', '(-) E coli O26 (en 325 g)',                                     'negativo','Negativo',        NULL),
('0151', '(-) E coli O45 (en 325 g)',                                     'negativo','Negativo',        NULL),
('0152', '(-) E coli O103 (en 325 g)',                                    'negativo','Negativo',        NULL),
('0153', '(-) E coli O111 (en 325 g)',                                    'negativo','Negativo',        NULL),
('0154', '(-) E coli O121 (en 325g)',                                     'negativo','Negativo',        NULL),
('0155', '(-) E coli O145 (en 325g)',                                     'negativo','Negativo',        NULL),
('0156', '(-) E coli STEC serotipo O (en 325 g)',                         'negativo','Negativo',        NULL),
('0157', '(-) E coli O157:NM (en 325g)',                                  'negativo','Negativo',        NULL),
('0158', '(-) Cloro Libre (ppm)',                                         'texto',   NULL,              NULL)
ON CONFLICT (codigo) DO UPDATE SET
  descripcion          = EXCLUDED.descripcion,
  tipo_campo           = EXCLUDED.tipo_campo,
  valor_predeterminado = EXCLUDED.valor_predeterminado,
  valor_referencia     = EXCLUDED.valor_referencia;
